#!/bin/bash
# $Id: wpgchk,v 1.2 2018/12/10 18:47:22 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/wpgchk,v $
# $Revision: 1.2 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: wpgchk,v 1.2 2018/12/10 18:47:22 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-k) keyterm $2; shift 2;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.2 $ $Date: 2018/12/10 18:47:22 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done
tmp=/tmp/$cmd.$$

config=${config:-/usr/local/etc/${cmd}.cf}
[ -r $config ] || { echo "$cmd: Can't find $config"
		   exit 1
}
eval `sed -ne '/^[^#]/p' $config`
printf "%30s %8s %8s %8s %8s %8s\n"  "URL"  $terms
for url in $urls; do
	wget -q -O $tmp  $url 
	(( ${#url} > 30 )) && url="${url:0:27}..."
	arr[0]=$url
	c=1
	for t in $terms ;do
		arr[$c]=`grep -i -o "$t[\. ]" $tmp|wc -l`
		c=$(( c + 1 ))
	done
	printf "%30s %8i %8i %8i %8i %8i\n" "${arr[0]}" "${arr[1]}" "${arr[2]}" "${arr[3]}" "${arr[4]}" "${arr[5]}"
	  
done

rm $tmp
